### ISSUE TITLE
Type definition file uses Wrappers instead of Primitive types for strings, booleans, numbers etc

### ISSUE THREAD

**Issue by AlphaLupine** [riffy-team/riffy#10]
### Issue description

Try to use this library with typescript, in the code example below, the arguement passed into the "get" method will be flagged as its defined as a type String instead of string.

### Code sample

```typescript
this.lavalink = new Riffy(this, lavaNode, {
            send: (payload) => {
                const guild = this.guilds.cache.get(payload.d.guild_id);
                if (guild) guild.shard.send(payload);
            },

        })
```

### Versions

riffy@1.0.3

### Issue priority

Medium (should be fixed soon)

**Comment by UnschooledGamer** [comment]
> ### Issue description
> 
> Try to use this library with typescript, in the code example below, the arguement passed into the "get" method will be flagged as its defined as a type String instead of string.
> 
> ### Code sample
> 
> ```typescript
> this.lavalink = new Riffy(this, lavaNode, {
>             send: (payload) => {
>                 const guild = this.guilds.cache.get(payload.d.guild_id);
>                 if (guild) guild.shard.send(payload);
>             },
> 
>         })
> ```
> 
> 
> ### Versions
> 
> riffy@1.0.3
> 
> ### Issue priority
> 
> Medium (should be fixed soon)

In typescript both `string` & `String` are seen as valid types it's one of either ways.

But if you compare it, ts will error.

**Comment by AlphaLupine** [comment]
Right, but this is exactly the issue and makes it a pain to use Riffy with Typescript. Because you are not using primitive types (the default type that typescript associates with strings, numbers, booleans etc) I will have to cast any time I pass data to and from your library. It would make sense to just change the type definitions to primitives which I believe is the practice recommended by Microsoft anyway.

**Comment by flameface** [comment]
try using riffy beta version `npm i riffy@beta` as it's totally written in ts

**Comment by feenko** [comment]
Still having the same issue on `riffy@beta`, any changes in that topic?
