### ISSUE TITLE
Improve playlist types

### ISSUE THREAD

**Issue by AlexInCube** [riffy-team/riffy#14]
### Feature

I am making the fancy messages about added songs and playlists, and when i working with playlist, i must grab data from tracks. And this data is not enough.
For example, if i want get source of playlist, i must write something like this
```ts
playlist.tracks[0].info.sourceName
```
This is not very safe.
Another example, to get the total length of songs, i must calculate it by myself by looping through the all tracks.
It would also be handy to have a formattedDuration field inside Track and Playlist.

### Ideal solution or implementation

For songs we have "Track" object, so i propose make "Playlist" object for playlists.
Playlists must contain URI to playlist, author of playlist, total length of all songs, source name, thumbnail uri.

### Alternative solutions or implementations

Implementation of Playlist
https://github.com/skick1234/DisTube/blob/main/src/struct/Playlist.ts
Implementation of Songs/Tracks
https://github.com/skick1234/DisTube/blob/main/src/struct/Song.ts

### Other context

You might be interested in why I'm showing examples from Distube? Because I'm trying to move from that library to Riffy.

**Comment by UnschooledGamer** [comment]
> ### Feature
> I am making the fancy messages about added songs and playlists, and when i working with playlist, i must grab data from tracks. And this data is not enough. For example, if i want get source of playlist, i must write something like this
> 
> ```ts
> playlist.tracks[0].info.sourceName
> ```
> 
> This is not very safe. Another example, to get the total length of songs, i must calculate it by myself by looping through the all tracks. It would also be handy to have a formattedDuration field inside Track and Playlist.
> 
> ### Ideal solution or implementation
> For songs we have "Track" object, so i propose make "Playlist" object for playlists. Playlists must contain URI to playlist, author of playlist, total length of all songs, source name, thumbnail uri.
> 
> ### Alternative solutions or implementations
> Implementation of Playlist https://github.com/skick1234/DisTube/blob/main/src/struct/Playlist.ts Implementation of Songs/Tracks https://github.com/skick1234/DisTube/blob/main/src/struct/Song.ts
> 
> ### Other context
> You might be interested in why I'm showing examples from Distube? Because I'm trying to move from that library to Riffy.


Riffy gives the Search Result/Response to Users what Lavalink returns.

- For `formattedDuration` I think it's better for the User Perform it (As depending upon what they want, It might be in `hhmmss` format Or might be `hours mins, secs` Or might be in different languages)

- Next up, proposal For additional for Playlists, As said before Riffy returns what it receives (As Lavalink by default doesn't provide those) 

- For Distube to Riffy it's worth noting that Riffy is a Lavalink Client that depends on Lavalink, Whereas Distube itself does all the stuffs(retrieving tracks, searching, etc) Doesn't Require a Additional Server for it.

You may find more about Lavalink at https://lavalink.dev

**Comment by AlexInCube** [comment]
Okay, well then I have other typing questions. 
It would be convenient if events were stored in enum. Like in Discord.js.
For example:
export enum Events {
    NodeConnect = 'nodeConnect',
    NodeReconnect = 'nodeReconnect'
}

**Comment by UnschooledGamer** [comment]
> Okay, well then I have other typing questions. It would be convenient if events were stored in enum. Like in Discord.js. For example:
> 
> ```ts
> export enum RiffyEvents {
>     NodeConnect = 'nodeConnect',
>     NodeReconnect = 'nodeReconnect'
> }
> ```

You've Actual use-case Or It's like it should be just cause it should.

**Comment by AlexInCube** [comment]
> > Okay, well then I have other typing questions. It would be convenient if events were stored in enum. Like in Discord.js. For example:
> > ```ts
> > export enum RiffyEvents {
> >     NodeConnect = 'nodeConnect',
> >     NodeReconnect = 'nodeReconnect'
> > }
> > ```
> 
> You've Actual use-case Or It's like it should be just cause it should.

Better autocomplete

**Comment by AlexInCube** [comment]
If we're using TypeScript, why don't we use types for hard constraints? This will allow us to catch errors faster in the future

**Comment by UnschooledGamer** [comment]
> If we're using TypeScript, why don't we use types for hard constraints? This will allow us to catch errors faster in the future

I don't I think I plan to have enum for RiffyEvents, Currently I'll have a `type/interface` like so:

```ts 
"nodeConnect": () => void;
```

This way Users could loop over via Typescript and get keys if they needed And Maybe in future we could have `RiffyEventsOnlyKeys` If needed.

Alright, Good Night. I'll see you & Respond back in the Morning. Bye And Good Night.

**Comment by UnschooledGamer** [comment]
Completed
