### ISSUE TITLE
Add "jump to song"

### ISSUE THREAD

**Issue by AlexInCube** [riffy-team/riffy#15]
### Feature

User want to jump to desired song in queue

### Ideal solution or implementation

Make jump() method in Player

**Comment by UnschooledGamer** [comment]
@AlexInCube Hey, It's Fair easier for you to do as `player.queue` is an array. You can use the `splice` to remove the number of tracks until the number you want to jump to(play next), And use `player.play`

Example:
Number to Track to Jump to & Play = `5`, Queue has `10` tracks

```js
async function skipTo(player, tracksToJump) {
  player.queue.splice(0 /* At Position */, tracksToJump - 1 /* Tracks to jump */)

 await player.play()
}

skipTo(player, 5) // Jumps 4 Tracks and plays the next(5th song), Jumped Tracks(i.e 5, 5 as Current Playing Track) are removed from the Queue.
```

I'll have A new Version Soon, So Replacing Tracks gets handled.


If you still think I should add it. Kindly Write Below.

Thanks,
UG.

**Comment by AlexInCube** [comment]
I have already implemented this function in your way. But I didn't use player.play(), I used player.stop(). Because player.play() caused some strange bugs for me.

Also, i make command /previous, but it doesn't work very well because the player can only store one previous song. 
It would be nice if Riffy collected already played songs into an array. 
And in Riffy parameters make the field savePreviousSongs: boolean, so that a person can decide what is more important to him, to save memory or to save previous songs in the queue.
```ts
const previousSong = riffyPlayer.previous;
if (!previousSong) return undefined;
riffyPlayer.queue.unshift(previousSong);
riffyPlayer.stop();
```

**Comment by UnschooledGamer** [comment]
Added it, set `multipleTrackHistory` in Riffy Options as per your needs (accepts `boolean | number`)

landed in 
`npm i https://pkg.pr.new/riffy-team/riffy@c2f70bc`

**Comment by AlexInCube** [comment]
Why you not public this to NPM?

**Comment by UnschooledGamer** [comment]
> Why you not public this to NPM? You want to test it?

It just helps out than frequent releases to npm. Nothing much it's same for the user.
