### ISSUE TITLE
this.send is not a function

### ISSUE THREAD

**Issue by AlexInCube** [riffy-team/riffy#17]
### Issue description

1. Install package from https://pkg.pr.new/riffy-team/riffy@c2f70bc
2. Try to play any song

### Code sample

```typescript
To realize that the problem is not in my code, I changed the package.json in the repository with the example (https://github.com/riffy-team/riffy-music-bot). 
“dependencies”: { “riffy”: “https://pkg.pr.new/riffy-team/riffy@c2f70bc” }
```

### Versions

riffy - https://pkg.pr.new/riffy-team/riffy@c2f70bc
djs - 14.14.1
windows 11
lavalink v4

### Issue priority

High (immediate attention needed)

**Comment by UnschooledGamer** [comment]
> ### Issue description
> 1. Install package from https://pkg.pr.new/riffy-team/riffy@c2f70bc
> 2. Try to play any song
> 
> ### Code sample
> ```ts
> To realize that the problem is not in my code, I changed the package.json in the repository with the example (https://github.com/riffy-team/riffy-music-bot). 
> “dependencies”: { “riffy”: “https://pkg.pr.new/riffy-team/riffy@c2f70bc” }
> ```
> 
> ### Versions
> riffy - https://pkg.pr.new/riffy-team/riffy@c2f70bc djs - 14.14.1 windows 11 lavalink v4
> 
> ### Issue priority
> High (immediate attention needed)

Fixed in https://pkg.pr.new/riffy-team/riffy@bcaaf04
