### ISSUE TITLE
Allow use Riffy.init() outside of onReady event

### ISSUE THREAD

**Issue by AlexInCube** [riffy-team/riffy#19]
### Feature

I don't like that my bot can start even when it failed to connect to Lavalink Nodes. But I can't initialize Riffy without providing client.id.

### Ideal solution or implementation

Remove the clientID argument from Riffy.init, and just send the "client" class to init.
This will allow you to use Riffy.init(client) not only inside the onReady event.

**Comment by Elitex07** [comment]
@AlexInCube Thanks for reaching us out. 

What are you actually seeking here?

**Comment by AlexInCube** [comment]
> @AlexInCube Thanks for reaching us out. 
> 
> What are you actually seeking here? You can still use riffy.init() outside of "ready" event in Djs.

When i do this, i get error about undefined in Client.user.id. So i must login bot to Discord and then init Riffy to fix this error.

**Comment by Elitex07** [comment]
If you want connect to the Nodes prior to the login process, then you can implement it before log-in

Do as follows:
```
<Riffy>.nodes.forEach((node) => <Riffy>.createNode(node));
```

**Comment by UnschooledGamer** [comment]
Worth Noting that LavaLink Requires the User/Client Id while connecting to the nodes. If you want to do connection stuffs outside of Ready Event then provide the client Id manually in `.init("My Bot's Id here")`

**Comment by AlexInCube** [comment]
> If you want connect to the Nodes prior to the login process, then you can implement it before log-in
> 
> Do as follows:
> 
> ```
> <Riffy>.nodes.forEach((node) => <Riffy>.createNode(node));
> ```

It doesn't work quite the way I wanted, I think I can catch the error via Try / Catch, but the errors go into the NodeError event.
I want to shut down the application via process.exit(), but I don't know what other types of errors can hit the nodeError event.

**Comment by AlexInCube** [comment]
> If you want connect to the Nodes prior to the login process, then you can implement it before log-in
> 
> Do as follows:
> 
> ```
> <Riffy>.nodes.forEach((node) => <Riffy>.createNode(node));
> ```

<Riffy>.createNode is not awaitable, so nodeConnect and nodeError events are still can output something after login to Discord.

**Comment by Elitex07** [comment]
@AlexInCube If `.createNode()` is not returning a promise then you should utilize Promise class in order to achieve the desired goal.

**Comment by AlexInCube** [comment]
> @AlexInCube If `.createNode()` is not returning a promise then you should utilize Promise class in order to achieve the desired goal.

I don't understand how to do it right. My `node.connected` is always false
```ts
async connectToNodes() {
    const createNodeAsync = (options: any) => {
      return new Promise((resolve, reject) => {
        const node = this.riffy.createNode(options);
        if (node.connected) {
          resolve(node);
        } else {
          reject(new Error('Node creation failed'));
        }
      });
    };

    for (const nodeOptions of this.riffy.nodes) {
      await createNodeAsync(nodeOptions);
    }
  }
```

**Comment by Elitex07** [comment]
`.createNode()` is not something instant. As I can see in the code, the implementation of Promise seems fine, but rather than checking `node.connected` in the very next line, you should utilize `nodeConnect` event emitted by `<Riffy>`

**Comment by UnschooledGamer** [comment]
> Now when i call riffy.init() in Discord.js onReady event, Riffy event NodeConnect triggered twice. Because riffy.createNode() trigger this event and riffy.init(). Also NodeConnect still make output after onReady event.

I'm unable to understand what's the actual problem? As connecting to the could take any amount of time, So `NodeConnect` getting emitted later, Seems fine.

**Comment by AlexInCube** [comment]
I want to make it so that while the bot doesn't connect to discord until it connects to all Lavalink nodes. My bot should display a message that it is ready to run after it has loaded all commands, connected to the database, etc.

**Comment by UnschooledGamer** [comment]
> I want to make it so that while the bot doesn't connect to discord until it connects to all Lavalink nodes. My bot should display a message that it is ready to run after it has loaded all commands, connected to the database, etc.

I see, You could use `once` from `events` class/module(by importing it). something like `await once(riffy, "nodeConnect")` more info at https://nodejs.org/api/events.html#eventsonceemitter-name-options

**Comment by AlexInCube** [comment]
I did what I wanted to do, but realised that Lavalink didn't respond well to it. I passed ‘1’ to Riffy.init() and then in the onReady event I made riffy.clientId = user.clientId. But Lavalink can't play songs in this case.
