### ISSUE TITLE
Not playing audio. [Fixed]

### ISSUE THREAD

**Issue by MoonCarli** [riffy-team/riffy#6]
### Issue description

My lavalink is working fine, my code is fine but the bot is not playing audio dont know why..
![Screenshot 2024-02-21 224646](https://github.com/riffy-team/riffy/assets/151431153/05f31f62-2263-4eec-97c8-8b4ec489f8a3)

### Code sample

```typescript
const { Client, EmbedBuilder, PermissionFlagsBits } = require("discord.js");

module.exports = {
  name: "play",
  category: "Music",
  aliases: ["p"],
  clientPermissions: [PermissionFlagsBits.Connect, PermissionFlagsBits.Speak],
  description: "Play songs",
  inVoice: true,

  execute: async (message, args, client) => {
    /**
     *
     * @param {Client} client
     * @param {CommandInteraction} interaction
     * @param {String} args
     * @returns
     */

    const query = args.join(' ');
    
    //This will not load the third-party link
    if (query.includes(`bit.ly`)) {
      return message.channel.send({
        embeds: [
          new EmbedBuilder()
            .setColor(client.embedColor)
            .setDescription(`**We Don't Support This Link**`),
        ],
      });
    }

    let player = client.riffy.players.get(message.guildId);

    if (!player)
      player = await client.riffy.createConnection({
        guildId: message.guild.id,
        voiceChannel: message.member.voice.channel.id,
        textChannel: message.channel.id,
        deaf: true,
      });

    const resolve = await client.riffy.resolve({
      query: query,
      requester: message.author,
    });
    const { loadType, tracks, playlistInfo } = resolve;

    if (loadType === "PLAYLIST_LOADED") {
      for (const track of resolve.tracks) {
        track.info.requester = message.author;
        player.queue.add(track);
      }

      await message.reply(
        `Added ${tracks.length} songs from ${playlistInfo.name} playlist.`
      );

      if (!player.playing && !player.paused) return player.play();
    } else if (loadType === "SEARCH_RESULT" || loadType === "TRACK_LOADED") {
      const track = tracks.shift();
      track.info.requester = message.author;

      player.queue.add(track);

      await message.reply(`Added **${track.info.title}** to the queue.`);

      if (!player.playing && !player.paused) return player.play();
    } else {
      return message.reply(`There were no results found for your query.`);
    }
  },
};
```

### Versions

"discord.js": "14.11",
"fs": "^0.0.1-security",
"musicard": "^2.0.3",
"riffy": "^1.0.3",
"riffy-spotify": "^1.0.2"

### Issue priority

High (immediate attention needed)

**Comment by UnschooledGamer** [comment]
> ### Issue description
> 
> My lavalink is working fine, my code is fine but the bot is not playing audio dont know why..
> ![Screenshot 2024-02-21 224646](https://github.com/riffy-team/riffy/assets/151431153/05f31f62-2263-4eec-97c8-8b4ec489f8a3)
> 
> 
> ### Code sample
> 
> ```typescript
> const { Client, EmbedBuilder, PermissionFlagsBits } = require("discord.js");
> 
> module.exports = {
>   name: "play",
>   category: "Music",
>   aliases: ["p"],
>   clientPermissions: [PermissionFlagsBits.Connect, PermissionFlagsBits.Speak],
>   description: "Play songs",
>   inVoice: true,
> 
>   execute: async (message, args, client) => {
>     /**
>      *
>      * @param {Client} client
>      * @param {CommandInteraction} interaction
>      * @param {String} args
>      * @returns
>      */
> 
>     const query = args.join(' ');
>     
>     //This will not load the third-party link
>     if (query.includes(`bit.ly`)) {
>       return message.channel.send({
>         embeds: [
>           new EmbedBuilder()
>             .setColor(client.embedColor)
>             .setDescription(`**We Don't Support This Link**`),
>         ],
>       });
>     }
> 
>     let player = client.riffy.players.get(message.guildId);
> 
>     if (!player)
>       player = await client.riffy.createConnection({
>         guildId: message.guild.id,
>         voiceChannel: message.member.voice.channel.id,
>         textChannel: message.channel.id,
>         deaf: true,
>       });
> 
>     const resolve = await client.riffy.resolve({
>       query: query,
>       requester: message.author,
>     });
>     const { loadType, tracks, playlistInfo } = resolve;
> 
>     if (loadType === "PLAYLIST_LOADED") {
>       for (const track of resolve.tracks) {
>         track.info.requester = message.author;
>         player.queue.add(track);
>       }
> 
>       await message.reply(
>         `Added ${tracks.length} songs from ${playlistInfo.name} playlist.`
>       );
> 
>       if (!player.playing && !player.paused) return player.play();
>     } else if (loadType === "SEARCH_RESULT" || loadType === "TRACK_LOADED") {
>       const track = tracks.shift();
>       track.info.requester = message.author;
> 
>       player.queue.add(track);
> 
>       await message.reply(`Added **${track.info.title}** to the queue.`);
> 
>       if (!player.playing && !player.paused) return player.play();
>     } else {
>       return message.reply(`There were no results found for your query.`);
>     }
>   },
> };
> ```
> 
> 
> ### Versions
> 
> "discord.js": "14.11",
> "fs": "^0.0.1-security",
> "musicard": "^2.0.3",
> "riffy": "^1.0.3",
> "riffy-spotify": "^1.0.2"
> 
> ### Issue priority
> 
> High (immediate attention needed)

Show me initialisation of Riffy & raw event code.

**Comment by MoonCarli** [comment]
> > ### Issue description
> > My lavalink is working fine, my code is fine but the bot is not playing audio dont know why..
> > ![Screenshot 2024-02-21 224646](https://private-user-images.githubusercontent.com/151431153/306715631-05f31f62-2263-4eec-97c8-8b4ec489f8a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4Njc3NjgsIm5iZiI6MTcwODg2NzQ2OCwicGF0aCI6Ii8xNTE0MzExNTMvMzA2NzE1NjMxLTA1ZjMxZjYyLTIyNjMtNGVlYy05N2M4LThiNGVjNDg5ZjhhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQxMzI0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDUxYzM5YTQxM2ExOTE3NzFlMWVkOWEyNmNlNzQ1Y2UyMjlmMTQzNTMwNGVkMDE1MDMzN2MwOGI4YTQyNTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B3dB_AxQ3MpbHwgKswldK9Fa1AWoL-7UcsioFaAdcvQ)
> > ### Code sample
> > ```ts
> > const { Client, EmbedBuilder, PermissionFlagsBits } = require("discord.js");
> > 
> > module.exports = {
> >   name: "play",
> >   category: "Music",
> >   aliases: ["p"],
> >   clientPermissions: [PermissionFlagsBits.Connect, PermissionFlagsBits.Speak],
> >   description: "Play songs",
> >   inVoice: true,
> > 
> >   execute: async (message, args, client) => {
> >     /**
> >      *
> >      * @param {Client} client
> >      * @param {CommandInteraction} interaction
> >      * @param {String} args
> >      * @returns
> >      */
> > 
> >     const query = args.join(' ');
> >     
> >     //This will not load the third-party link
> >     if (query.includes(`bit.ly`)) {
> >       return message.channel.send({
> >         embeds: [
> >           new EmbedBuilder()
> >             .setColor(client.embedColor)
> >             .setDescription(`**We Don't Support This Link**`),
> >         ],
> >       });
> >     }
> > 
> >     let player = client.riffy.players.get(message.guildId);
> > 
> >     if (!player)
> >       player = await client.riffy.createConnection({
> >         guildId: message.guild.id,
> >         voiceChannel: message.member.voice.channel.id,
> >         textChannel: message.channel.id,
> >         deaf: true,
> >       });
> > 
> >     const resolve = await client.riffy.resolve({
> >       query: query,
> >       requester: message.author,
> >     });
> >     const { loadType, tracks, playlistInfo } = resolve;
> > 
> >     if (loadType === "PLAYLIST_LOADED") {
> >       for (const track of resolve.tracks) {
> >         track.info.requester = message.author;
> >         player.queue.add(track);
> >       }
> > 
> >       await message.reply(
> >         `Added ${tracks.length} songs from ${playlistInfo.name} playlist.`
> >       );
> > 
> >       if (!player.playing && !player.paused) return player.play();
> >     } else if (loadType === "SEARCH_RESULT" || loadType === "TRACK_LOADED") {
> >       const track = tracks.shift();
> >       track.info.requester = message.author;
> > 
> >       player.queue.add(track);
> > 
> >       await message.reply(`Added **${track.info.title}** to the queue.`);
> > 
> >       if (!player.playing && !player.paused) return player.play();
> >     } else {
> >       return message.reply(`There were no results found for your query.`);
> >     }
> >   },
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Versions
> > "discord.js": "14.11",
> > "fs": "^0.0.1-security",
> > "musicard": "^2.0.3",
> > "riffy": "^1.0.3",
> > "riffy-spotify": "^1.0.2"
> > ### Issue priority
> > High (immediate attention needed)
> 
> Show me initialisation of Riffy & raw event code.

hmhm i forgot to do this in raw code.. my bad.. thanks for helping
