### ISSUE TITLE
Node Voice Region Choosing Different Node then Choosed Node

### ISSUE THREAD

**Issue by UnschooledGamer** [riffy-team/riffy#7]
## 🚥 Status
Open - If you have any better ideas for this do tell me here or mention and tell me on discord, do tell me if you're interested in resolving it
### Issue description

**Explanation:** After creating a player with `createConnection` along with the region option/parameter set, Creates an Player on the Node matching that "region", If you try searching with `resolve` method it will search on other Node and plays on the other Node(previously selected Region Node) That's The main Issue here. It's caused By `leastUsedNodes` sorting method in Riffy.

**My Solution:** To add a `node` parameter riffy `resolve` method that way the **user can parse the player's node** while searching. 
Another Solution is to modify the `leastUsedNodes` But it's not that much reliable compared to 1st solution.
Better Solution I have is to have resolve method in the Player Class itself & Have `node` parameter in Riffy `resolve` method too.

## Steps to Reproduce:

1. Create a Player with `createConnection`
2. Provide the `region` parameter
3. Search something with riffy Resolve method
4. You'll see in the logs it searches on one Node and plays on other Node(It's supposed to search this Node only, As that's the Node filtered by Region and created on it)
5. Make sure to have `regions` defined in the NodeOptions.

### Versions

- riffy **riffy-team/riffy#fix/user-bugs-feats**

### Issue priority

Medium (should be fixed soon)

**Comment by Elitex07** [comment]
Fixed in release 1.0.5
